### PR TITLE
Feature/uplaod image

### PR DESCRIPTION
**Pull request by Eddie-Kuo**
Added functionality for user to select an image from camera roll and to add to profile sign up form

### CODE REVIEW

**Comment by samirspatel** [comment]
I assume this is not happening to you, but I'm getting this error 
Screenshot 2024-09-10 at 5 52 21 PM

**Comment by samirspatel** [comment]
Code looks good, but im not seeing a way to upload the avatar?

**Comment by Eddie-Kuo** [comment]
Changed the implementation of checking if a user is new or returning with userStatus state = "New" | "Returning"
- userStatus added to initialLayout dependency array so routing will commence when status is set

**Review by samirspatel — APPROVED** [review]
Code looks good. I think we can merge this one in and then focus on getting the main entry point to read from the session to see if they have entered their number before. If so, then take them to the authenticated section

**Pull request merged**
